### ISSUE TITLE
Some problem with downloading PressureVisionDB Dataset 

### ISSUE THREAD

**Issue by gmindflow** [facebookresearch/PressureVision#1]
While downloading the file, when it reaches about 59% of downloading the "**9010_cray_crane.zip**" file, it suddenly stops and gives an output that says, 

_FileNotFoundError: [Errno 2] No such file or directory: 'data/test/9010_cray_crane.zip_

Could you please check if it works? I'm wondering if I'm the only one having this issue.

Thanks.

**Comment by pgrady3** [comment]
Yes, the downloading script is currently not very robust. Each of the downloaded files are very large, ~30 GB, and any network errors cause the downloader to fail. You can try to download the file in your browser (links in the script). I’m working on a better download method and a smaller dataset, which I hope to release in the next week.

**Comment by zlz212** [comment]
something wrong while prediction trainer, done loading dataset is ok, finished training epoch has someting wrong; error is ValueError: Expected both predictions and target to be either 1- or 2-dimensional tensors, but got 3 and 3; I wonder how to solve it.

Thanks!

**Comment by pgrady3** [comment]
Closing this because the original question was answered, and we released the smaller version of the dataset.

@zlz212 Can you open a new issue and share the stack trace for your exception? What you shared isn't really enough to be useful.
